// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmJhuk78NAinYQBaJXKrj1y29Frrr2_bo',
    appId: '1:874990871595:web:0bec14a248abaf093a366e',
    messagingSenderId: '874990871595',
    projectId: 'act13-45f60',
    authDomain: 'act13-45f60.firebaseapp.com',
    storageBucket: 'act13-45f60.firebasestorage.app',
    measurementId: 'G-KP2HSDH82X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZCJ7zfdtkKxSgu5uCbt8INyGzZ2Ib3d0',
    appId: '1:874990871595:android:1d507c0dacd1a9783a366e',
    messagingSenderId: '874990871595',
    projectId: 'act13-45f60',
    storageBucket: 'act13-45f60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDINe2yfLGvjjlxWqiHqfAA_Caj0d-0p7I',
    appId: '1:874990871595:ios:238bb86adf2d02063a366e',
    messagingSenderId: '874990871595',
    projectId: 'act13-45f60',
    storageBucket: 'act13-45f60.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDINe2yfLGvjjlxWqiHqfAA_Caj0d-0p7I',
    appId: '1:874990871595:ios:238bb86adf2d02063a366e',
    messagingSenderId: '874990871595',
    projectId: 'act13-45f60',
    storageBucket: 'act13-45f60.firebasestorage.app',
    iosBundleId: 'com.example.act13',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmJhuk78NAinYQBaJXKrj1y29Frrr2_bo',
    appId: '1:874990871595:web:63a77f570eafed323a366e',
    messagingSenderId: '874990871595',
    projectId: 'act13-45f60',
    authDomain: 'act13-45f60.firebaseapp.com',
    storageBucket: 'act13-45f60.firebasestorage.app',
    measurementId: 'G-SBSTY6STCE',
  );
}
